name: Python CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-in-container:
    runs-on: ubuntu-latest
    container:
      image: zpoettker/ai-job-matcher:v1
      
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Run tests in container
        run: pytest tests/
